Repository gisce/apply_pr, pull requests merged in 2023-01, with the labels that each got.

#127 Check prs using giscemultitools
  apply_pr/fabfile.py
  requirements.txt
Labels: enhancement

#128 PRs without milestone as ERROR (check_prs)
  apply_pr/fabfile.py
Labels: bug, to be merged

#129 ci auto version
  .bumpversion.cfg
  .github/workflows/version.yml
Labels: patch

#130 fix repo ci
  .github/workflows/version.yml
Labels: patch
