Repository gisce/apply_pr, pull requests merged in 2024-03, with the labels that each got.

#142 PY3 compat
  apply_pr/cli.py
  apply_pr/fabfile.py
  requirements.txt
Labels: major

#147 Ensure deploy/patches on first diff apply
  apply_pr/fabfile.py
Labels: enhancement, to be merged, patch

#148 Decode command
  apply_pr/fabfile.py
Labels: patch

#149 Fix decode
  apply_pr/fabfile.py
Labels: patch

#150 Fix comparing unicode to decoded text
  apply_pr/fabfile.py
Labels: patch
